package hu.blackbelt.judo.zeta.transformation.core.performance;

import hu.blackbelt.judo.zeta.annotation.*;
import hu.blackbelt.judo.zeta.transformation.core.TransformationContext;
import hu.blackbelt.judo.zeta.transformation.core.TransformFunction;
import hu.blackbelt.judo.zeta.transformation.core.TransformGuard;
import org.eclipse.emf.ecore.*;

/**
 * Transformation rules for synthetic model benchmark testing.
 *
 * <p>These rules transform synthetic PSM-style models generated by
 * {@link SyntheticModelGenerator} into corresponding target model elements.
 * Includes greedy and lazy variations, guard support, and metrics collection.</p>
 */
@hu.blackbelt.judo.zeta.annotation.TransformationContext(source = EPackage.class, target = EPackage.class)
public class BenchmarkRules {

    /**
     * Default constructor required for TransformationRegistry.
     */
    public BenchmarkRules() {
    }

    // ==================== Package Rule ====================

    /**
     * Greedy rule: transforms EPackage → EPackage.
     */
    @TransformRule(name = "CreatePackage", description = "Transform EPackage to EPackage")
    @Greedy
    @Transform(type = EPackage.class)
    @To(type = EPackage.class)
    public TransformFunction<EPackage, EPackage> createPackage() {
        return (s, ctx) -> {
            EPackage t = ctx.createTarget(EPackage.class);
            t.setName(s.getName() + "_target");
            t.setNsURI(s.getNsURI() + "/target");
            return t;
        };
    }

    // ==================== Class Rules ====================

    /**
     * Greedy rule: transforms EClass → EClass.
     */
    @TransformRule(name = "CreateClass", description = "Transform EClass to EClass")
    @Greedy
    @Transform(type = EClass.class)
    @To(type = EClass.class)
    public TransformFunction<EClass, EClass> createClass() {
        return (s, ctx) -> {
            EClass t = ctx.createTarget(EClass.class);
            t.setName(s.getName() + "_target");
            return t;
        };
    }

    /**
     * Guard: checks for guard-marker annotation.
     * Returns false if the source has a guard-marker with reject=true.
     */
    public static class GuardRejector implements TransformGuard {
        @Override
        public boolean evaluate(EObject source, TransformationContext context) {
            if (source instanceof EClass) {
                EClass clazz = (EClass) source;
                for (EAnnotation annotation : clazz.getEAnnotations()) {
                    if ("guard-marker".equals(annotation.getSource())) {
                        String reject = annotation.getDetails().get("reject");
                        return !"true".equals(reject);
                    }
                }
            }
            return true;
        }
    }

    /**
     * Guarded class rule with @Greedy @Guard annotation.
     */
    @TransformRule(name = "CreateClassGuarded", description = "Guarded EClass transformation")
    @Greedy
    @Guard(method = "checkGuard")
    @Transform(type = EClass.class)
    @To(type = EClass.class)
    public TransformFunction<EClass, EClass> createClassGuarded() {
        return (s, ctx) -> {
            EClass t = ctx.createTarget(EClass.class);
            t.setName(s.getName() + "_guarded");
            return t;
        };
    }

    /**
     * Guard check method.
     */
    public boolean checkGuard(EObject source, TransformationContext context) {
        return new GuardRejector().evaluate(source, context);
    }

    // ==================== Attribute Rules ====================

    /**
     * Lazy rule: transforms EAttribute → EAttribute with type resolution.
     */
    @TransformRule(name = "CreateAttribute", description = "Transform EAttribute to EAttribute")
    @Lazy
    @Transform(type = EAttribute.class)
    @To(type = EAttribute.class)
    public TransformFunction<EAttribute, EAttribute> createAttribute() {
        return (s, ctx) -> {
            EAttribute t = ctx.createTarget(EAttribute.class);
            t.setName(s.getName() + "_target");
            if (s.getEType() != null) {
                // Try to find the equivalent type in target
                EClassifier targetType = ctx.equivalent(s.getEType(), EClassifier.class);
                if (targetType != null) {
                    t.setEType(targetType);
                }
            }
            return t;
        };
    }

    // ==================== Reference Rules ====================

    /**
     * Lazy rule: transforms EReference → EReference.
     */
    @TransformRule(name = "CreateReference", description = "Transform EReference to EReference")
    @Lazy
    @Transform(type = EReference.class)
    @To(type = EReference.class)
    public TransformFunction<EReference, EReference> createReference() {
        return (s, ctx) -> {
            EReference t = ctx.createTarget(EReference.class);
            t.setName(s.getName() + "_target");
            if (s.getEType() != null) {
                EClass targetType = ctx.equivalent(s.getEType(), EClass.class);
                if (targetType != null) {
                    t.setEType(targetType);
                }
            }
            t.setContainment(s.isContainment());
            return t;
        };
    }

    // ==================== Operation Rules ====================

    /**
     * Lazy rule: transforms EOperation → EOperation.
     */
    @TransformRule(name = "CreateOperation", description = "Transform EOperation to EOperation")
    @Lazy
    @Transform(type = EOperation.class)
    @To(type = EOperation.class)
    public TransformFunction<EOperation, EOperation> createOperation() {
        return (s, ctx) -> {
            EOperation t = ctx.createTarget(EOperation.class);
            t.setName(s.getName() + "_target");
            return t;
        };
    }
}
