package hu.blackbelt.judo.zeta.transformation.core;

/*-
 * #%L
 * Judo :: Zeta :: Transformation Core
 * %%
 * Copyright (C) 2018 - 2024 BlackBelt Technology
 * %%
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * with the GNU Classpath Exception which is
 * available at https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 * #L%
 */

import hu.blackbelt.judo.zeta.annotation.Greedy;
import hu.blackbelt.judo.zeta.annotation.Lazy;
import hu.blackbelt.judo.zeta.annotation.TransformRule;
import hu.blackbelt.judo.zeta.common.ExtensionMethodRegistry;
import hu.blackbelt.judo.zeta.common.ModelProvider;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.*;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.xmi.XMIResource;
import org.eclipse.emf.ecore.xmi.impl.XMIResourceFactoryImpl;
import org.junit.jupiter.api.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.*;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.jupiter.api.Assertions.*;

/**
 * TDD test for reproducing XMI ID context pollution when nested @Lazy @Greedy rules
 * are triggered via ctx.equivalent() from within a parent rule.
 *
 * <p>Issue: When RelationFeatureView rule (parent) calls ctx.equivalent() to trigger
 * RelationFeatureViewBackAction rule (child), the child's auto-generated XMI ID
 * incorrectly uses the parent rule's name instead of its own.</p>
 *
 * <p>Expected: Child rule's XMI ID should contain the child rule's name.</p>
 * <p>Actual (bug): Child rule's XMI ID contains the parent rule's name.</p>
 */
@DisplayName("Nested @Lazy @Greedy XMI ID Context Tests")
class NestedLazyGreedyXmiIdTest {

    private static final Logger log = LoggerFactory.getLogger(NestedLazyGreedyXmiIdTest.class);

    // Rule names matching the real-world scenario
    private static final String PARENT_RULE = "ParentViewRule";
    private static final String CHILD_ACTION_RULE = "ChildActionRule";

    // Track the auto-generated ID before custom ID is set
    static AtomicReference<String> childAutoGeneratedId = new AtomicReference<>();
    static AtomicReference<String> childCustomId = new AtomicReference<>();
    static AtomicReference<String> parentAutoGeneratedId = new AtomicReference<>();

    private ResourceSet sourceResourceSet;
    private ResourceSet targetResourceSet;
    private Resource sourceResource;
    private Resource targetResource;

    @BeforeEach
    void setUp() {
        Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap()
                .put("*", new XMIResourceFactoryImpl());

        sourceResourceSet = new ResourceSetImpl();
        targetResourceSet = new ResourceSetImpl();
        sourceResource = sourceResourceSet.createResource(URI.createURI("test://source.xmi"));
        targetResource = targetResourceSet.createResource(URI.createURI("test://target.xmi"));

        // Reset tracking variables
        childAutoGeneratedId.set(null);
        childCustomId.set(null);
        parentAutoGeneratedId.set(null);
    }

    private TransformationContext createContext(TransformationRegistry registry) {
        ExtensionMethodRegistry extensionRegistry = new ExtensionMethodRegistry();
        ModelProvider modelProvider = new TestModelProvider();

        TransformationContext ctx = new TransformationContext(
                modelProvider, sourceResourceSet, targetResourceSet, extensionRegistry);
        ctx.setTargetPackage(EcorePackage.eINSTANCE);
        ctx.registerResource("source", sourceResourceSet);
        ctx.registerResource("target", targetResourceSet);
        ctx.setTransformationRegistry(registry);

        // Enable structured IDs with global prefix (like the real transformation)
        ctx.setUseStructuredIds(true);
        ctx.setGlobalIdPrefix("TestPrefix");

        return ctx;
    }

    private EClass createSourceElement(String name, String xmiId) {
        EClass ec = EcoreFactory.eINSTANCE.createEClass();
        ec.setName(name);
        sourceResource.getContents().add(ec);
        if (sourceResource instanceof XMIResource) {
            ((XMIResource) sourceResource).setID(ec, xmiId);
        }
        return ec;
    }

    // ==================== Transformation Rules ====================

    /**
     * Parent rule: @Greedy, creates EDataType (simulating PageDefinition).
     * Calls ctx.equivalent() to trigger child rule.
     */
    @hu.blackbelt.judo.zeta.annotation.TransformationContext(source = EClass.class, target = EDataType.class)
    public static class ParentViewTransformation {

        @TransformRule(name = PARENT_RULE, description = "Parent rule that triggers child via equivalent()")
        @Greedy
        public TransformFunction<EClass, EDataType> parentViewRule() {
            return (source, ctx) -> {
                log.debug("ParentViewRule executing for source: {}", source.getName());

                // Create parent target (like PageDefinition)
                // At this point, auto-generated ID is set using currentExecutingRule
                EDataType target = ctx.createTarget(EDataType.class);
                target.setName(source.getName() + "_ParentView");

                // Add to resource so XMI ID can be applied
                ctx.addToResource(target);

                // Capture the auto-generated ID before we override it
                parentAutoGeneratedId.set("(auto-id-set-by-createTarget)");

                // Set custom XMI ID (like the real transformation does)
                String customId = "TestPrefix/(source/_testSourceId)/" + PARENT_RULE;
                ctx.setElementId(target, customId);
                log.debug("ParentViewRule set custom ID: {}", customId);

                // Trigger child rule via equivalent() - THIS IS WHERE THE BUG MANIFESTS
                // The child rule should execute with currentExecutingRule = CHILD_ACTION_RULE
                EAnnotation childAction = ctx.equivalent(source, EAnnotation.class, CHILD_ACTION_RULE);
                if (childAction != null) {
                    log.debug("ParentViewRule got child action with source attr: {}", childAction.getSource());
                }

                return target;
            };
        }
    }

    /**
     * Child rule: @Lazy @Greedy, creates EAnnotation (simulating Action).
     * Should use its own rule name for XMI ID, not parent's.
     */
    @hu.blackbelt.judo.zeta.annotation.TransformationContext(source = EClass.class, target = EAnnotation.class)
    public static class ChildActionTransformation {

        @TransformRule(name = CHILD_ACTION_RULE, description = "Child rule triggered by parent")
        @Lazy
        @Greedy
        public TransformFunction<EClass, EAnnotation> childActionRule() {
            return (source, ctx) -> {
                log.debug("ChildActionRule executing for source: {}", source.getName());

                // CRITICAL: At this point, currentExecutingRule SHOULD be CHILD_ACTION_RULE
                // If it's still PARENT_RULE, then the auto-generated ID will be wrong

                // Create child target (like Action)
                EAnnotation target = ctx.createTarget(EAnnotation.class);
                target.setSource(source.getName() + "_ChildAction");

                // Add to resource so XMI ID can be applied
                ctx.addToResource(target);

                // The auto-generated ID was already set by createTarget()
                // We can't directly read it, but we'll verify via XMI resource later

                // Set custom XMI ID
                String customId = "TestPrefix/(source/_testSourceId)/" + CHILD_ACTION_RULE;
                childCustomId.set(customId);
                ctx.setElementId(target, customId);
                log.debug("ChildActionRule set custom ID: {}", customId);

                return target;
            };
        }
    }

    /**
     * Child transformation that captures the auto-generated ID.
     */
    @hu.blackbelt.judo.zeta.annotation.TransformationContext(source = EClass.class, target = EAnnotation.class)
    public static class IdCapturingChildTransformation {

        @TransformRule(name = CHILD_ACTION_RULE, description = "Child rule that captures auto-ID")
        @Lazy
        @Greedy
        public TransformFunction<EClass, EAnnotation> childActionRule() {
            return (source, ctx) -> {
                log.debug("IdCapturingChildRule executing for source: {}", source.getName());

                // Create child target - this is where the auto-ID is generated
                EAnnotation target = ctx.createTarget(EAnnotation.class);

                // Try to capture the auto-generated ID by looking in pending XMI IDs
                try {
                    java.lang.reflect.Field pendingXmiIdsField =
                            ctx.getClass().getDeclaredField("pendingXmiIds");
                    pendingXmiIdsField.setAccessible(true);
                    @SuppressWarnings("unchecked")
                    Map<EObject, String> pendingXmiIds =
                            (Map<EObject, String>) pendingXmiIdsField.get(ctx);
                    String autoId = pendingXmiIds.get(target);
                    childAutoGeneratedId.set(autoId);
                    log.info("Captured auto-generated ID via reflection: {}", autoId);
                } catch (Exception e) {
                    log.warn("Could not capture auto-generated ID: {}", e.getMessage());
                }

                target.setSource(source.getName() + "_ChildAction");

                // Add to resource so XMI ID can be applied
                ctx.addToResource(target);

                // Set custom XMI ID
                String customId = "TestPrefix/(source/_testSourceId)/" + CHILD_ACTION_RULE;
                childCustomId.set(customId);
                ctx.setElementId(target, customId);

                return target;
            };
        }
    }

    /**
     * Test ModelProvider implementation.
     */
    static class TestModelProvider implements ModelProvider {
        @Override
        @SuppressWarnings("unchecked")
        public <T extends EObject> Collection<T> getAllContents(ResourceSet resourceSet, Class<T> type) {
            List<T> results = new ArrayList<>();
            for (Resource resource : resourceSet.getResources()) {
                TreeIterator<EObject> iterator = resource.getAllContents();
                while (iterator.hasNext()) {
                    EObject obj = iterator.next();
                    if (type.isInstance(obj)) {
                        results.add((T) obj);
                    }
                }
            }
            return results;
        }
    }

    // ==================== Tests ====================

    @Nested
    @DisplayName("XMI ID Context Isolation")
    class XmiIdContextIsolationTests {

        @Test
        @DisplayName("Child rule's target should have correct XMI ID after nested execution")
        void childRuleShouldHaveCorrectXmiId() {
            // Create transformation registry and context
            TransformationRegistry registry = new TransformationRegistry();
            registry.register(ParentViewTransformation.class);
            registry.register(ChildActionTransformation.class);

            TransformationContext ctx = createContext(registry);

            // Create source element
            EClass source = createSourceElement("TestSource", "_testSourceId");

            // Execute parent rule which triggers child rule via equivalent()
            TransformRuleDescriptor parentRule = registry.getRuleByName(PARENT_RULE);
            assertNotNull(parentRule, "Parent rule should be registered");

            EDataType parentTarget = (EDataType) parentRule.execute(source, ctx);
            assertNotNull(parentTarget, "Parent rule should create target");

            // Get the child target that was created
            EAnnotation childTarget = ctx.equivalent(source, EAnnotation.class, CHILD_ACTION_RULE);
            assertNotNull(childTarget, "Child target should exist after parent rule execution");

            // Commit staged elements to apply XMI IDs
            ctx.commitStagedElements();

            // Get XMI IDs from resource
            XMIResource xmiResource = (XMIResource) targetResource;
            String actualParentId = xmiResource.getID(parentTarget);
            String actualChildId = xmiResource.getID(childTarget);

            log.info("Parent target XMI ID: {}", actualParentId);
            log.info("Child target XMI ID: {}", actualChildId);

            // CRITICAL ASSERTION: Child's ID should contain CHILD rule name
            String expectedChildId = "TestPrefix/(source/_testSourceId)/" + CHILD_ACTION_RULE;
            assertEquals(expectedChildId, actualChildId,
                    "Child's XMI ID should be the custom ID set by child rule");

            // Verify child ID does NOT contain ONLY parent rule name
            assertFalse(actualChildId.endsWith("/" + PARENT_RULE),
                    "Child's XMI ID should NOT end with parent rule name '" + PARENT_RULE + "'");

            // Verify parent's ID is correct
            String expectedParentId = "TestPrefix/(source/_testSourceId)/" + PARENT_RULE;
            assertEquals(expectedParentId, actualParentId,
                    "Parent's XMI ID should be the custom ID set by parent rule");
        }

        @Test
        @DisplayName("XMI lookup by parent ID should not return child element (stale index bug)")
        void xmiLookupByParentIdShouldNotReturnChild() {
            // Create transformation registry and context
            TransformationRegistry registry = new TransformationRegistry();
            registry.register(ParentViewTransformation.class);
            registry.register(ChildActionTransformation.class);

            TransformationContext ctx = createContext(registry);

            // Create source element
            EClass source = createSourceElement("TestSource", "_testSourceId");

            // Execute parent rule
            TransformRuleDescriptor parentRule = registry.getRuleByName(PARENT_RULE);
            EDataType parentTarget = (EDataType) parentRule.execute(source, ctx);

            // Verify that equivalent() for parent type returns parent, not child
            EDataType foundParent = ctx.equivalent(source, EDataType.class, PARENT_RULE);
            assertSame(parentTarget, foundParent, "equivalent() for parent rule should return parent target");

            // Verify that equivalent() for child type returns child
            EAnnotation childTarget = ctx.equivalent(source, EAnnotation.class, CHILD_ACTION_RULE);
            assertNotNull(childTarget, "equivalent() for child rule should return child target");

            // CRITICAL: The types should be distinct - no cross-contamination
            assertFalse(childTarget instanceof EDataType,
                    "Child target should NOT be EDataType (parent type)");
            assertFalse(parentTarget instanceof EAnnotation,
                    "Parent target should NOT be EAnnotation (child type)");
        }
    }

    @Nested
    @DisplayName("Stale Index Entry Cleanup")
    class StaleIndexEntryTests {

        @Test
        @DisplayName("setElementId should allow ID changes without stale entries affecting lookups")
        void setElementIdShouldHandleIdChanges() {
            // Create transformation context
            TransformationRegistry registry = new TransformationRegistry();
            TransformationContext ctx = createContext(registry);

            // Create an element and add to resource
            EAnnotation element = EcoreFactory.eINSTANCE.createEAnnotation();
            element.setSource("TestElement");
            targetResource.getContents().add(element);

            // Set initial ID (simulating auto-generated ID with WRONG rule name)
            String wrongId = "TestPrefix/(source/_test)/WrongRuleName";
            ctx.setElementId(element, wrongId);

            // Change the ID to correct one (simulating custom ID override)
            String correctId = "TestPrefix/(source/_test)/CorrectRuleName";
            ctx.setElementId(element, correctId);

            // Apply pending IDs
            ctx.commitStagedElements();

            // Get actual ID from XMI resource
            XMIResource xmiResource = (XMIResource) targetResource;
            String actualId = xmiResource.getID(element);

            // Verify the final ID is the correct one
            assertEquals(correctId, actualId,
                    "Element should have the correct (final) XMI ID");
        }

        /**
         * This test reproduces the stale index entry bug where changing an element's
         * XMI ID doesn't remove the old entry from pendingXmiIdIndex, causing
         * findByXmiId(oldId) to incorrectly return the element.
         *
         * <p>BUG BEHAVIOR (current): findByXmiId(wrongId) returns the element (stale entry)</p>
         * <p>EXPECTED BEHAVIOR: findByXmiId(wrongId) returns null after ID change</p>
         */
        @Test
        @DisplayName("findByXmiId should return null for old ID after ID change (BUG REPRODUCTION)")
        void findByXmiIdShouldReturnNullForOldId() throws Exception {
            // Create transformation context
            TransformationRegistry registry = new TransformationRegistry();
            TransformationContext ctx = createContext(registry);

            // Create an element and add to resource
            EAnnotation element = EcoreFactory.eINSTANCE.createEAnnotation();
            element.setSource("TestElement");
            targetResource.getContents().add(element);

            // Set initial ID (simulating auto-generated ID with WRONG rule name)
            String wrongId = "TestPrefix/(source/_test)/WrongRuleName";
            ctx.setElementId(element, wrongId);

            // At this point, pendingXmiIdIndex[wrongId] -> element

            // Change the ID to correct one (simulating custom ID override)
            String correctId = "TestPrefix/(source/_test)/CorrectRuleName";
            ctx.setElementId(element, correctId);

            // At this point:
            // - pendingXmiIdIndex[correctId] -> element (correct)
            // - pendingXmiIdIndex[wrongId] -> element (STALE - should be removed!)

            // Use reflection to call findByXmiId (it's private)
            java.lang.reflect.Method findByXmiIdMethod =
                    TransformationContext.class.getDeclaredMethod("findByXmiId", String.class, Class.class);
            findByXmiIdMethod.setAccessible(true);

            // Test 1: Looking up correctId should return the element
            EAnnotation foundByCorrectId =
                    (EAnnotation) findByXmiIdMethod.invoke(ctx, correctId, EAnnotation.class);
            assertSame(element, foundByCorrectId,
                    "findByXmiId(correctId) should return the element");

            // Test 2: Looking up wrongId should return NULL (stale entry should be removed)
            // THIS IS THE BUG: Currently returns the element because stale entry remains
            EAnnotation foundByWrongId =
                    (EAnnotation) findByXmiIdMethod.invoke(ctx, wrongId, EAnnotation.class);

            // CRITICAL ASSERTION: This will FAIL with current buggy code
            // because the stale entry is not removed from pendingXmiIdIndex
            assertNull(foundByWrongId,
                    "findByXmiId(wrongId) should return null after ID was changed to correctId. " +
                    "This indicates a stale index entry bug: the old ID is still in pendingXmiIdIndex.");
        }

        /**
         * This test verifies that setting the same ID twice doesn't cause issues.
         */
        @Test
        @DisplayName("setElementId with same ID should not cause problems")
        void setElementIdWithSameIdShouldWork() throws Exception {
            // Create transformation context
            TransformationRegistry registry = new TransformationRegistry();
            TransformationContext ctx = createContext(registry);

            // Create an element and add to resource
            EAnnotation element = EcoreFactory.eINSTANCE.createEAnnotation();
            element.setSource("TestElement");
            targetResource.getContents().add(element);

            // Set ID
            String id = "TestPrefix/(source/_test)/SomeRule";
            ctx.setElementId(element, id);

            // Set same ID again (no-op)
            ctx.setElementId(element, id);

            // Use reflection to call findByXmiId
            java.lang.reflect.Method findByXmiIdMethod =
                    TransformationContext.class.getDeclaredMethod("findByXmiId", String.class, Class.class);
            findByXmiIdMethod.setAccessible(true);

            // Should still find the element
            EAnnotation found = (EAnnotation) findByXmiIdMethod.invoke(ctx, id, EAnnotation.class);
            assertSame(element, found, "findByXmiId should return the element after setting same ID twice");
        }
    }

    @Nested
    @DisplayName("Auto-generated ID Context Verification")
    class AutoGeneratedIdContextTests {

        /**
         * This test verifies that when createTarget() is called inside a child rule
         * triggered by ctx.equivalent(), the auto-generated XMI ID uses the child
         * rule's name, not the parent rule's name.
         *
         * This is the core bug we're trying to catch.
         */
        @Test
        @DisplayName("createTarget() in child rule should use child rule context for auto-ID")
        void createTargetInChildShouldUseChildContext() {
            // Create transformation registry with ID-capturing child rule
            TransformationRegistry registry = new TransformationRegistry();
            registry.register(ParentViewTransformation.class);
            registry.register(IdCapturingChildTransformation.class);

            TransformationContext ctx = createContext(registry);

            // Create source element
            EClass source = createSourceElement("TestSource", "_testSourceId");

            // Execute parent rule
            TransformRuleDescriptor parentRule = registry.getRuleByName(PARENT_RULE);
            parentRule.execute(source, ctx);

            // Check the captured auto-generated ID
            String capturedAutoId = childAutoGeneratedId.get();
            log.info("Captured child auto-generated ID: {}", capturedAutoId);

            if (capturedAutoId != null) {
                // CRITICAL: The auto-generated ID should contain CHILD rule name
                assertTrue(capturedAutoId.contains(CHILD_ACTION_RULE),
                        "Auto-generated ID should contain child rule name '" + CHILD_ACTION_RULE +
                        "', but was: " + capturedAutoId);

                // It should NOT contain only the parent rule name
                assertFalse(capturedAutoId.endsWith("/" + PARENT_RULE),
                        "Auto-generated ID should NOT end with parent rule name '" + PARENT_RULE +
                        "', but was: " + capturedAutoId);
            }
        }
    }
}
